[package]
name = "presentation"
version = "0.1.0"
edition = "2024"

[dependencies]
app.workspace = true
geometry.workspace = true
gles.workspace = true
layout.workspace = true
render.workspace = true
wayland.workspace = true
window.workspace = true

[dev-dependencies]
atlas.workspace = true
paint.workspace = true
ring.workspace = true
wayland = { workspace = true, features = ["fake"] }
